# Generated by Django 4.1.4 on 2022-12-31 04:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombookapp', '0002_roomdata'),
    ]

    operations = [
        migrations.CreateModel(
            name='userchk',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('user_fname', models.CharField(max_length=100, null=True)),
                ('user_lname', models.CharField(max_length=100, null=True)),
                ('user_idcard', models.CharField(max_length=13, null=True)),
                ('user_phone', models.CharField(max_length=12)),
            ],
        ),
    ]
