# Generated by Django 4.1.4 on 2022-12-31 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('roombookapp', '0003_userchk'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userchk',
            name='user_fname',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='userchk',
            name='user_idcard',
            field=models.CharField(max_length=13),
        ),
        migrations.AlterField(
            model_name='userchk',
            name='user_lname',
            field=models.CharField(max_length=100),
        ),
    ]
